version: "3.8"

services:
  monitor-client-app:
    build: .
    container_name: application-monitor
    ports:
      - "${PORT}:3000"   # Maps host port from PORT (e.g. 5050) to container port 5005
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # access to deamon
    restart: unless-stopped
